-- JITSW initial schema.
-- Generated by hand to match src/store/schema.ts.
-- Re-generate via drizzle-kit once monorepo hoisting is sorted.

CREATE TABLE IF NOT EXISTS "packets" (
  "id" text PRIMARY KEY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "expires_at" timestamp with time zone,
  "agent" jsonb NOT NULL,
  "kind" text NOT NULL,
  "title" text NOT NULL,
  "summary" text,
  "surface" jsonb NOT NULL,
  "hints" jsonb,
  "gbrain_citations" jsonb,
  "matrix_room_id" text
);

CREATE INDEX IF NOT EXISTS "packets_created_at_idx" ON "packets" ("created_at");
CREATE INDEX IF NOT EXISTS "packets_agent_idx" ON "packets" ("agent");

CREATE TABLE IF NOT EXISTS "actions" (
  "id" text PRIMARY KEY NOT NULL,
  "packet_id" text NOT NULL,
  "timestamp" timestamp with time zone DEFAULT now() NOT NULL,
  "name" text NOT NULL,
  "surface_id" text NOT NULL,
  "source_component_id" text NOT NULL,
  "context" jsonb
);

CREATE INDEX IF NOT EXISTS "actions_packet_idx" ON "actions" ("packet_id");
CREATE INDEX IF NOT EXISTS "actions_timestamp_idx" ON "actions" ("timestamp");
